name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    name: "Build for Linux"
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22

    - name: Build
      run: go build -ldflags="-X main.Environment=production -X main.CommitHash=${{github.sha}} -X main.SentryDSN=${{secrets.SENTRY_DSN}} -X main.AnalyticsEndpoint=${{NIKSIONLINE_URL}}" -o build/niksibot -v .
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: niksibot-linux
        path: build/niksibot
        if-no-files-found: error

  build-win:
    name: "Build for Windows"
    runs-on: windows-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22

    - name: Build
      run: go build -ldflags="-X main.Environment=production -X main.CommitHash=${{github.sha}} -X main.SentryDSN=${{secrets.SENTRY_DSN}} -X main.AnalyticsEndpoint=${{NIKSIONLINE_URL}}" -o build/niksibot.exe -v .
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: niksibot-win
        path: build/niksibot.exe
        if-no-files-found: error

  publish-sentry-release:
    name: "Publish Sentry release"
    runs-on: ubuntu-latest
    needs: [build-linux, build-win]
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish Sentry release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
        with:
          environment: production
          version_prefix: "niksibot-v2@"
          version: ${{github.sha}}
